### ISSUE TITLE
Bug in Export function

### ISSUE THREAD

**Issue by srimathigopi12** [BALKANGraph/OrgChartJS#341]
Hi,

When the organization structure is larger, the export functions have some issues.

1. Export PDF is too slow
2. Export PNG is just exporting partly. It cut the right side off. 

The below image shows only part of the org structure for your reference. 
![image](https://user-images.githubusercontent.com/63232544/78549516-b5ab0680-782c-11ea-8692-76546bb78679.png)

Please help me to fix this issue

**Comment by plamen-peshev** [comment]
we will investigate the issue and will get back to you

**Comment by srimathigopi12** [comment]
Hi, 

Is there any updates about this issue? Could you tell me when it can be fixed please...

**Comment by srimathigopi12** [comment]
> we will investigate the issue and will get back to you

Hi, 

Is there any updates about this issue?

**Comment by pushpender98** [comment]
Hi 

Any update over here?

**Comment by srimathigopi12** [comment]
> Hi
> 
> Any update over here?

Not yet.. I'm waiting for Mr. Peshev's reply

**Comment by ZornitsaSerbezova** [comment]
The issue with the PNG is addressed in the latest export service v1.3.9

**Comment by srimathigopi12** [comment]
> The issue with the PNG is addressed in the latest export service v1.3.9

I updated with the latest export service and tried with more than 900 nodes. I still have the same problem. Please help me to fix it

**Comment by ZornitsaSerbezova** [comment]
Hi srimathigopi12,
We were able to reproduce the issue and have logged it in our system.
Thank you for reporting it.

**Comment by pushpender98** [comment]
Any update to this, Is this fixed?

**Comment by nbpro** [comment]
@srimathigopi12 @pushpender98 @plamen-peshev 
The problem is view box, for larger maps you need to increase view box width and height.
I was also facing this issue and i have manually increased the vb dimensions :
```
const svg = document.querySelector('svg');
        if (svg && data.vb){
          data.vb[2] = data.vb[2]* 1.1;
          data.vb[3] = data.vb[3]* 1.1;
          svg.setAttribute("viewBox", data.vb);
        }
```
and then changed puppeter configuration to 
```const puppeteerParams = {
  headless: true,
  ignoreHTTPSErrors: true,
  args: ['--no-sandbox', '--disable-setuid-sandbox','--start-maximized' ]
};```
