### ISSUE TITLE
pdfPrevUI not found

### ISSUE THREAD

**Issue by LuisECP** [BALKANGraph/OrgChartJS#599]
I'm using angular 9 I import the library like this "import OrgChart from '@ balkangraph / orgchart.js';"

but when trying to use pdfPrevUI it can't find it. Has it happened to someone?

![2021-10-05_20h10_23](https://user-images.githubusercontent.com/54037353/136125466-d1ff7982-727b-4c0f-acb2-c868bc5e3985.png)

even if I run the code with the error, if it shows the preview but with missing elements.

![2021-10-05_20h12_45](https://user-images.githubusercontent.com/54037353/136125476-1c9de7a3-f530-4e64-a842-0c63c0a17c2d.png)

**Comment by ZornitsaPesheva** [comment]
Hi LuisECP,

We have fixed this in the latest version (7.13.08)

**Comment by LuisECP** [comment]
Thanks I upgrade the last version and it works

But certain properties of the preview window are still not displayed.

![2021-10-05_20h12_45](https://user-images.githubusercontent.com/54037353/136419673-234dbf34-c0d4-4eda-a764-d946060e5568.png)


.-I found that to change the elements of the pdf preview I will use: "OrgChart.loc.ppdfSave = 'Save';"

but "loc" does not exist. Is there something I am missing?
